version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Localp@55"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always